name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm --version  # Debugging step

      - name: Install dependencies using pnpm
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: List output files (Debugging step)
        run: ls -la

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          ENABLE_ORYX_BUILD: "true"   # Ensures Azure uses our build command
          SKIP_NPM_INSTALL: "true"    # Prevents Azure from running 'npm install'
          skip_app_build: "true"      # Ensures Azure does NOT build again
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_SKY_01604C500 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"        # Change this to the correct folder (e.g., "dist", "build", ".next/out")
          api_location: "" 
          output_location: "out" 

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_SKY_01604C500 }}
          action: "close"
